name: loading_indicator
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  extensions:
    path: ../extensions

dev_dependencies:
  flutter_lints: ^3.0.1